<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/FelipeAlbarelli/Donut-Svelte-ThreeJs-Threlte-Glsl/public/assets/JustDonut.gltf
-->

<script  >
// @ts-nocheck

  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { FakeGlowMaterial, useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/assets/JustDonut.gltf')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}

    <T.Mesh

    >
      <T.Mesh 
        geometry={gltf.nodes.Torus001.geometry} 
        position={[0, 0, 0]} 
      >

        <slot name="mat-top" />
      </T.Mesh>
    </T.Mesh>
    <T.Mesh geometry={gltf.nodes.Torus.geometry} position={[0, 0., 0]} >
      <slot name="mat-bot" />
    
    </T.Mesh>

    <!-- <T.Mesh geometry={gltf.nodes.Torus_1.geometry} material={mat2 ?? gltf.materials['Material.001']} position={[0, 0, 0]} /> -->
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
